
version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: leyo007/get-started:part2
     
        
    steps:
       - checkout
         # start proprietary DB using private Docker image
         # with credentials stored in the UI
         - run: |
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             
             docker run -d leyo007/get-started:part2
         # build the application image #docker pull leyo007/get-started:part2
         - run: docker build -t leyo007/get-started .

         # deploy the image
         - run: docker push leyo007/get-started:part3
