version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker run -d leyo007/getstarted:part2

     # build the application image
     - run: docker build -t leyo007/getstarted:part2 .

     # deploy the image
     - run: docker push leyo007/getstarted:part2
