version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: |
        docker image ls
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker run -d leyo007/get-started:part2
     - run: docker build -t leyo007/get-started:part3 .
     
     - run: docker push leyo007/get-started:part3
