version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

        docker run -d leyo007/get-started:part2
        docker image ls
      # build the application image
     - run: docker build -t leyo007/get-started:part3 .
     
      # deploy the image
     - run: docker push leyo007/get-started:part3
